GET http://localhost:4000

###
POST http://localhost:4000/register
Content-Type: application/json

{
    "username": "Wow",
    "password": "Nigga"
}
###

GET http://localhost:4000/login
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.MTIzNDU.gVEwAEw_NBnJktQbFLhzPEb8VyuZugkjATA6gDOoLPk
###
GET http://localhost:4000/posts
###
POST http://localhost:4000/posts
Content-Type: application/json

{
    "username": "TEstttqrwqer",
    "title": "i ate a dog",
    "description": "woof woof rip lollololol"
}

###
POST http://localhost:4000/chat
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.MTIzNDU.gVEwAEw_NBnJktQbFLhzPEb8VyuZugkjATA6gDOoLPk
Content-Type: application/json

{
    "content": "fhasjhroiqw"
}

###
GET https://postellar-server.herokuapp.com/posts
# Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.MTIzNDU.gVEwAEw_NBnJktQbFLhzPEb8VyuZugkjATA6gDOoLPk

###
GET http://postellar-server.herokuapp.com/login

###